on:
    schedule:
      # Runs daily at 2 AM UTC
      - cron: "0 2 * * *"
    workflow_dispatch: # Allow manual runs
  
  jobs:
    update-badges:
      name: Update README with Credly Badges
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Update Badges
          uses: programfiction/badge-readme@main
          with:
            CREDLY_USER: ${{ github.actor }} # Uses your GitHub username
            NUMBER_LAST_BADGES: 10 # Show last 10 badges (0 = all)